const products = [
  {
    productId: "PROD001",
    storeName: "Amazon",
    productName: "Apple AirPods Pro",
    description:
      "Active noise cancellation for immersive sound. Transparency mode for hearing the world around you.",
    price: 249.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/61SUj2aKoEL._AC_SL1500_.jpg",
  },
  {
    productId: "PROD002",
    storeName: "Amazon",
    productName: "Kindle Paperwhite",
    description:
      "Waterproof, high-resolution display, and weeks of battery life.",
    price: 139.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/61hPhRZx84L._AC_UY218_.jpg",
  },
  {
    productId: "PROD003",
    storeName: "Amazon",
    productName: "Instant Pot Duo 7-in-1",
    description:
      "7-in-1 multi-functional pressure cooker that replaces multiple kitchen appliances.",
    price: 99.95,
    category: "Home",
    imageUrl: "https://m.media-amazon.com/images/I/61WZ8UkkReL._AC_UL320_.jpg",
  },
  {
    productId: "PROD004",
    storeName: "Best Buy",
    productName: "Sony 55-inch 4K Ultra HD TV",
    description:
      "Experience stunning 4K picture quality with vibrant colors and sharp details.",
    price: 599.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/81h-r-3hioL._AC_UY218_.jpg",
  },
  {
    productId: "PROD005",
    storeName: "Best Buy",
    productName: "Sony PlayStation 5",
    description:
      "Next-gen gaming console with ultra-high-speed SSD and immersive 3D audio.",
    price: 499.99,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/61998CBydXL._AC_UY218_.jpg",
  },
  {
    productId: "PROD006",
    storeName: "Target",
    productName: "Nike Air Max 270",
    description:
      "Revolutionary cushioning and a sleek design for all-day comfort.",
    price: 150.0,
    category: "Clothing",
    imageUrl: "https://m.media-amazon.com/images/I/61hhB82FgGL._AC_UL320_.jpg",
  },
  {
    productId: "PROD007",
    storeName: "Target",
    productName: "Adidas Backpack",
    description: "Durable and stylish backpack for everyday use.",
    price: 40.0,
    category: "Accessories",
    imageUrl: "https://m.media-amazon.com/images/I/81hpFNU+UWL._AC_UL320_.jpg",
  },
  {
    productId: "PROD008",
    storeName: "Walmart",
    productName: "Dyson V11 Cordless Vacuum",
    description: "Powerful suction and up to 60 minutes of fade-free cleaning.",
    price: 549.99,
    category: "Home",
    imageUrl: "https://m.media-amazon.com/images/I/61xIxBIiTML._AC_UY218_.jpg",
  },
  {
    productId: "PROD009",
    storeName: "Walmart",
    productName: "DeWalt 20V Max Cordless Drill",
    description:
      "High-performance drill with a compact and lightweight design.",
    price: 129.0,
    category: "Tools",
    imageUrl: "https://m.media-amazon.com/images/I/51WPS11IuSL._AC_UL320_.jpg",
  },
  {
    productId: "PROD010",
    storeName: "Walmart",
    productName: "Instant Pot Duo 7-in-1",
    description:
      "7-in-1 multi-functional pressure cooker that replaces multiple kitchen appliances.",
    price: 99.95,
    category: "Home",
    imageUrl: "https://m.media-amazon.com/images/I/61WZ8UkkReL._AC_UL320_.jpg",
  },
  {
    productId: "PROD011",
    storeName: "Costco",
    productName: "Kirkland Signature Coffee",
    description: "Premium coffee beans for a rich and smooth flavor.",
    price: 15.0,
    category: "Groceries",
    imageUrl: "https://m.media-amazon.com/images/I/81Flo4xyQWL._AC_UL320_.jpg",
  },
  {
    productId: "PROD012",
    storeName: "Costco",
    productName: "Dyson V11 Cordless Vacuum",
    description: "Powerful suction and up to 60 minutes of fade-free cleaning.",
    price: 549.99,
    category: "Home",
    imageUrl: "https://m.media-amazon.com/images/I/61xIxBIiTML._AC_UY218_.jpg",
  },
  {
    productId: "PROD013",
    storeName: "Home Depot",
    productName: "DeWalt 20V Max Cordless Drill",
    description:
      "High-performance drill with a compact and lightweight design.",
    price: 129.0,
    category: "Tools",
    imageUrl: "https://m.media-amazon.com/images/I/51WPS11IuSL._AC_UL320_.jpg",
  },
  {
    productId: "PROD014",
    storeName: "Home Depot",
    productName: "Ryobi 18V Cordless Drill",
    description: "Affordable and reliable cordless drill for DIY projects.",
    price: 79.99,
    category: "Tools",
    imageUrl: "https://m.media-amazon.com/images/I/516H0VcEX1L._AC_UL320_.jpg",
  },
  {
    productId: "PROD015",
    storeName: "IKEA",
    productName: "Billy Bookcase",
    description: "A timeless design that fits perfectly in any room.",
    price: 79.99,
    category: "Furniture",
    imageUrl: "https://m.media-amazon.com/images/I/51DbXNjLjdL._AC_UL320_.jpg",
  },
  {
    productId: "PROD016",
    storeName: "IKEA",
    productName: "POÄNG Armchair",
    description: "Comfortable and stylish armchair for your living room.",
    price: 99.99,
    category: "Furniture",
    imageUrl: "https://m.media-amazon.com/images/I/41aLt0fvXrL._AC_UL320_.jpg",
  },
  {
    productId: "PROD017",
    storeName: "Starbucks",
    productName: "Starbucks Coffee Mug",
    description: "A classic white ceramic mug with the Starbucks logo.",
    price: 12.99,
    category: "Kitchen",
    imageUrl: "https://m.media-amazon.com/images/I/410epLkArAL._AC_UL320_.jpg",
  },
  {
    productId: "PROD018",
    storeName: "Apple Store",
    productName: "iPhone 15 Pro",
    description: "The ultimate iPhone with a titanium design and A17 Pro chip.",
    price: 999.0,
    category: "Electronics",
    imageUrl: "https://m.media-amazon.com/images/I/81SigpJN1KL._AC_UY218_.jpg",
  },
  {
    productId: "PROD019",
    storeName: "Nike",
    productName: "Nike Tech Fleece Joggers",
    description: "Soft, comfortable joggers with a modern fit.",
    price: 100.0,
    category: "Clothing",
    imageUrl: "https://m.media-amazon.com/images/I/61sXk8gd5ML._AC_UL320_.jpg",
  },
  {
    productId: "PROD020",
    storeName: "Nike",
    productName: "Nike Air Force 1 Shoes",
    description: "Iconic sneakers with a timeless design.",
    price: 110.0,
    category: "Clothing",
    imageUrl: "https://m.media-amazon.com/images/I/61xCZR-TBmL._AC_UL320_.jpg",
  },
];
export default products;
